version: '3'

networks:
  default:
    name: opentelemetry-demo
    driver: bridge

services:
  app:
    build: ../app/
    container_name: app
    depends_on:
      - otel
    ports:
      - "80:80"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel:4318"
      OTEL_EXPORTER_OTLP_METRICS_PROTOCOL: "http/protobuf"
    networks:
      - default
  otel:
    build: .
    container_name: otel
    command: ["--config=/etc/otelcol/otel-config-local.yaml"]
    ports:
      - "4317"
      - "4318:4318"
    networks:
      - default