version: '3'

networks:
  otel-demo:
    driver: bridge

services:
  app:
    build: ../app/
    depends_on:
      - otel
    ports:
      - "80:80"
    environment:
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "http://localhost:4317"
      OTEL_EXPORTER_OTLP_METRICS_PROTOCOL: "grpc"
    networks:
      - otel-demo
  otel:
    build: .
    command: ["--config=/etc/otelcol/otel-config-local.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - otel-demo