services:
  app:
    build: ../app/
    depends_on:
      - otel
    ports:
      - "80:80"
    environment:
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "localhost:4317"
  otel:
    build: .
    ports:
      - "4317:4317"