receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  debug:
    verbosity: detailed
  prometheusremotewrite/thanos:
    endpoint: "localhost:10908/api/v1/receive"
    namespace: test-app
    external_labels:
      thanos: "true"
    resource_to_telemetry_conversion:
      enabled: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      exporters: [debug, prometheusremotewrite/thanos]
    logs:
      receivers: [otlp]
      exporters: [debug]